### ISSUE TITLE
irdb csv parsing does not handle fields with embedded commas

### ISSUE THREAD

**Issue by asedeno** [bengtmartensson/RemoteLocator#2]
https://github.com/probonopd/irdb/blob/master/codes/Denon/Receiver/2%2C-1.csv#L87-L88

These two lines are where [parsing](https://github.com/bengtmartensson/RemoteLocator/blob/ea6ada77ce699b17c54c581723064894387161ab/src/main/java/org/harctoolbox/remotelocator/IrdbScrap.java#L104-L122) will fail on account of function names containing commas.

My [PR](https://github.com/bengtmartensson/IrScrutinizer/pull/428) handled this with some special casing I did not particularly like. Given that this issue is only likely to arise from commas in function names, splitting from the right with a limit would be an easy fix if we had `rsplit()`.

This is not particularly urgent given it only affects two codes for one remote in all of the irdb.

**Comment by bengtmartensson** [comment]
Well, this is rather "not implemented yet" than a traditional bug. Also to implement is the quoting of the CSV files containing commas (IrdbScrap.print).
